# Generated by Django 5.0.6 on 2024-06-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="draf",
            field=models.BooleanField(default=False),
        ),
    ]
