# Generated by Django 5.0.6 on 2024-07-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_blog_draf"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="img",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
