# Generated by Django 5.0.6 on 2024-07-04 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_blog_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
